plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.6'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	maven {
		url "https://plugins.gradle.org/m2/"
	}
}

subprojects {
	apply plugin: "java"
	apply plugin: "java-library"
	apply plugin: 'org.springframework.boot'
	apply plugin: "io.spring.dependency-management"

	repositories {
		mavenCentral()
		maven { url 'https://repo.spring.io/snapshot' }
	}

	dependencies {
		implementation 'org.springframework.boot:spring-boot-starter-web'
		implementation 'org.springframework.boot:spring-boot-starter-validation'
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

project(':common') {
	dependencies {
		api project(':dynamodb')
		api 'org.springframework.boot:spring-boot-starter-security'
		api 'com.auth0:java-jwt:4.2.2'
		implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	}

	jar {
		enabled = true
		archiveBaseName.set("common")
	}

	bootJar {
		enabled = false
	}
}

project(':products') {
	dependencies {
		implementation project(':common')
		implementation project(':dynamodb')
		developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	}

	bootRun {
		workingDir = rootProject.projectDir
	}

	jar {
		enabled = false
		archiveBaseName.set("products")
	}

	bootJar {
		enabled = true
		archiveFileName.set("products.jar")
		launchScript()
	}
}

project(':orders') {
	dependencies {
		implementation project(':common')
		implementation project(':dynamodb')
		developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	}

	bootRun {
		workingDir = rootProject.projectDir
	}

	jar {
		enabled = false
		archiveBaseName.set("orders")
	}

	bootJar {
		enabled = true
		archiveFileName.set("orders.jar")
		launchScript()
	}
}

project(':users') {
	dependencies {
		implementation project(':common')
		developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	}

	bootRun {
		workingDir = rootProject.projectDir
	}

	jar {
		enabled = false
		archiveBaseName.set("users")
	}

	bootJar {
		enabled = true
		archiveFileName.set("users.jar")
		launchScript()
	}
}
