server:
  port: 8080

spring:
  application:
    name: orders-api
  profiles:
    include:
      - common
      - dynamodb
    group:
      local: dynamodb-local,common-local
      dev: dynamodb-dev
  docker:
    compose:
      enabled: false
